version: '3.9'

services:
  type-safety-postgres:
    image: postgres:latest
    ports:
      - ${DB_PORT}:${DB_PORT}
    volumes:
      - /var/lib/postgresql/data/
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB}
      - PGPORT=${DB_PORT}
      - PGDATA=/var/lib/postgresql/data/
    command: -p ${DB_PORT}
    networks:
      - app-network

  server-app:
    build: .
    depends_on:
      - type-safety-postgres
    env_file:
      - .env
      - .env.docker
    ports:
      - ${APP_PORT}:${APP_PORT}
    networks:
      - app-network

networks:
  app-network:
    driver: bridge